### ISSUE TITLE
HTTP 429 Too Many Requests.

### ISSUE THREAD

**Issue by Najmul-Hasan-Sobuj** [ai-genie/chatgpt-vscode#47] opened 2023-04-02 13:43 UTC
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

HTTP 429 Too Many Requests. Too many requests try again later. You can clear your API Key from VS Code's [secrets storage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) with Genie: Clear API Key command. Potential reasons:

You exceeded your current quota, please check your plan and billing details
You are sending requests too quickly
The engine is currently overloaded, please try again later.
See https://platform.openai.com/docs/guides/error-codes for more details.
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

no.  i don't change any

**Comment by genieai-info** [comment] 2023-04-02 23:48
@Najmul-Hasan-Sobuj please follow the troubleshooting guide to verify your account has enough credits and has not expired. Closing as dupe of #25

**Closed by genieai-info** 2023-04-02 23:48 UTC
Labels: bug
