### ISSUE TITLE
An error occured with Azure GPT-4 Chat Completion, error 400: Unsupported data type

### ISSUE THREAD

**Issue by maxdata** [ai-genie/chatgpt-vscode#72] opened 2023-04-17 21:47 UTC
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

An error occured with Azure GPT-4 Chat Completion, error 400: Unsupported data type

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

use Azure GPT-4 Chat completion

**Comment by genieai-info** [comment] 2023-04-17 21:52
Hi there - this is dupe of https://github.com/ai-genie/chatgpt-vscode/issues/50. Please also make sure you select the right base model you used for your Azure OpenAI deployment as noted in [FAQ](https://github.com/ai-genie/chatgpt-vscode#faq)

> Azure OpenAI Service: Unsupported data type Error: This means you didn't select the right base model for your Azure OpenAI service. Make sure to select the base GPT model you used to create your Azure OpenAI Service deployment

**Closed by genieai-info** 2023-04-17 21:52 UTC
Labels: bug
