### ISSUE TITLE
Eventually stops working - too many tokens [max_tokens]

### ISSUE THREAD

**Issue by Image8080** [ai-genie/chatgpt-vscode#43] opened 2023-03-31 04:31 UTC
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

This was working reall great until it eventually fails with this:
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4237 tokens (141 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

Once this happens, not reset, restarts or even changing api key works.

Windows 10, python 3.10, latest version of vscode and extensions

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

using defaults but did try changing max_tokens - fro 64 to 2048 - no luck, eventually it will just error out. The only way to recover seems to be reset session altogether (or remove add a NEW api key). You the lose all context and have to start again.

**Comment by Image8080** [comment] 2023-03-31 07:12
Most of the time I can clear by reseting session and api_key however this loses context and I have to start again - not really useable in real life. Has anyoone else seen this?

**Comment by 1gn0r3d** [comment] 2023-03-31 11:17
Yeah, I have the same issue.
I always have to request a new api key when this happens
(and it happens quite often)

**Comment by genieai-info** [comment] 2023-03-31 11:52
Hi - this happens because your conversation is likely long. And for GPT-* models, the extension provided the whole history for better accuracy.

However, we see the limitations that may bring and we made a change in v0.0.5 to only append system message + last conversation + new conversation to your question. So that you have both historical context without consuming your tokens for the whole conversation.

Please upgrade to v0.0.5 to get the updates

Dupe of #35

**Closed by genieai-info** 2023-03-31 11:52 UTC
Labels: bug

**Comment by Image8080** [comment] 2023-04-07 06:39
I figured it was something like that, its just that when it does happen, you have crea/refresh the page for it to work again
