### ISSUE TITLE
Doesn't work in editor view

### ISSUE THREAD

**Issue by beraaren** [ai-genie/chatgpt-vscode#161] opened 2024-03-01 06:35 UTC
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

It doesn't work on ... model. And I can't change the model in the settings.

An error occured. ChatGPT error 404: {
    "error": {
        "message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I'm using default settings

### Additional context

azure api kulanımıyorum. muhtamelen benim api ile alakalı bir problem var. ayarlara editor view için model özelleştirilme eklenmeli

**Comment by robhung** [comment] 2024-03-02 21:26
Duplicate of #150

**Comment by abdielalvarez** [comment] 2024-03-14 03:44
So the topic does not die, i have exactly the same issue, windows 11 en VSC, it really does not work anything in the editor view, but the directly commands works, the editor view is the cool feature, so it is a real shame that it does not work

**Comment by gitkoyot** [comment] 2024-03-17 18:25
The model selection for "editor view" would be useful feature. Now it is not usable :(

**Comment by rtonerii** [comment] 2024-03-19 17:17
I am having the same problem.

**Comment by pifabs** [comment] 2024-04-01 05:52
I'm experiencing the same issue.

**Comment by mandikaye** [comment] 2024-06-08 16:23
I'm experiencing the same issue.

**Comment by genieai-info** [comment] 2024-06-14 13:22
Hi everyone - The new models are now available in v0.0.11 please update your extensions. gpt-4o is set as default. The editor view issue is also fixed and now it uses your selected model instead of the deprecated legacy OpenAI model.

**Closed by genieai-info** 2024-06-14 13:22 UTC
Labels: bug
