### ISSUE TITLE
invalid_request_error (Exceeded max_tokens allowed by the model)

### ISSUE THREAD

**Issue by freefoxcm** [ai-genie/chatgpt-vscode#35] opened 2023-03-28 10:37 UTC
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

HTTP 400 Bad Request. You may have exhausted your OpenAI subscription allowance or have an expired account. You can clear your API Key from VS Code's [secrets storage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) with Genie: Clear API Key command. Check your allowance and account's expiration date here: https://platform.openai.com/account/usage

{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4790 tokens (2742 in the messages, 2048 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

gpt-3.5-turbo

**Comment by 1gn0r3d** [comment] 2023-03-29 11:46
I have the same bug

**Comment by genieai-info** [comment] 2023-03-29 11:53
Hi - this is related to the max_tokens you have in your settings. The default is 2048 tokens spared for the response. If you request + response is larger than your model's max_token count, you will see this error from OpenAI. You should adjust your maxTokens (Setting: `"genieai.openai.maxTokens"`) or break your prompts into chunks so that OpenAI responds within the maxTokens limits

The error message is printed means that your prompt/question contains 2742 tokens and the response is larger than max allowed(4097 - 2742):
`This model's maximum context length is 4097 tokens. However, you requested 4790 tokens (2742 in the messages, 2048 in the completion). Please reduce the length of the messages or completion.`

We are working to introduce a counter so that you maximize the token usage. However, you could still face this issue if you are prompting with a very long message. 

Closing this as expected and will track the max token calculation with this issue: https://github.com/ai-genie/chatgpt-vscode/issues/20

**Closed by genieai-info** 2023-03-29 11:53 UTC
Labels: bug

**Comment by freefoxcm** [comment] 2023-03-30 00:55
Hi, my individual conversations are not too long. This problem only occurs after a certain amount of time has passed, for example, when I ask it to help me write some code or copywriting. I wonder if there is too much additional previous chat content attached during each request?

**Comment by Dinoraptor101** [comment] 2023-03-30 15:29
> 

Oh I see it could be caused by enabling historical in the plugin, while GPT does have the context in the back-end so it should understand historical without appending I'll try updating the setting on VScode to see if this remedies the issue., I also created a duplicate issue. I'm going to close it

**Comment by genieai-info** [comment] 2023-03-31 11:52
Hi - this happens because your conversation is likely long. And for GPT-* models, the extension provided the whole history for better accuracy.

However, we see the limitations that may bring and we made a change in v0.0.5 to only append system message + last conversation + new conversation to your question. So that you have both historical context without consuming your tokens for the whole conversation.

Please upgrade to v0.0.5 to get the updates

**Comment by cyicz123** [comment] 2023-03-31 17:11
> Hi - this happens because your conversation is likely long. And for GPT-* models, the extension provided the whole history for better accuracy.
> 
> However, we see the limitations that may bring and we made a change in v0.0.5 to only append system message + last conversation + new conversation to your question. So that you have both historical context without consuming your tokens for the whole conversation.
> 
> Please upgrade to v0.0.5 to get the updates

Hi there! Could you please tell how the official openai website chat.openai.com handles the context understanding issue? I noticed that the ChatGPT-Next-Web project has a feature that automatically compresses chat history to support long conversations while also saving your tokens.  Excuse me, esteemed author. Do you think it would be possible to incorporate this particular feature into this project?  Would love to hear your thoughts on the matter. Thanks!

**Comment by freefoxcm** [comment] 2023-04-03 00:22
Hi,It is true that the problem did not recur after upgrading to the new version, but if interspersed with some less relevant questions, the answer is not accurate enough.The ChatGPT-Next-Web project provides a setting to adjust the number of historical messages, while in the ChuanhuChatGPT project, Do Do looks like it provides a summary of previous content to handle this issue, so you can refer to that!
